### ISSUE TITLE
Terminal vim runtime error

### ISSUE THREAD

**Issue by steadystatic** [michalliu/sourcebeautify.vim#15]
I am getting this error when trying to use the plugin on .html file and invoking via <Leader>SB:

 beautifying, please wait...
 Error detected while processing function <SNR>125_beautify..319..javascript#runtime#evalScript:
 line   39:
 There's a problem while evaluating javascript code
 Javascript Interpreter => /System/Library/Frameworks/JavaScriptCore.framework/Resources/jsc
 Details => SyntaxError: Unexpected end of script
 Exception: ReferenceError: Can't find variable: process
 /Users/steadystatic/.janus/jsruntime.vim/autoload/javascript/jsrunner/runjs.js:109:16
 readSTDIN@/Users/steadystatic/.janus/jsruntime.vim/autoload/javascript/jsrunner/runjs.js:99:21
 global code@/Users/steadystatic/.janus/jsruntime.vim/autoload/javascript/jsrunner/runjs.js:104:10

**Comment by steadystatic** [comment]
I have node running:
node -v
v0.10.33

Perhaps I should use the other library?

**Comment by pvamshi** [comment]
Got the same problem

**Comment by alexanderlperez** [comment]
Does this have a solution? Running Vim 7.74.712, Node 0.12.4

**Comment by michalliu** [comment]
I recently bought a macbook pro. You can try update your [jsruntime](https://github.com/michalliu/jsruntime.vim) from here the error will go away.
