### ISSUE TITLE
Doesn't work on css files.

### ISSUE THREAD

**Issue by 8HNHoFtE** [michalliu/sourcebeautify.vim#5]
In a regular Css file when i hit <leader> sb, i get the following error in vim:

beautifying, please wait...  
Error detected while processing function <SNR>52_beautify..185..javascript#runtime#evalScript:  
line   38:  
There's a problem while evaluating javascript code

**Comment by michalliu** [comment]
@kyounger  I recently updated the plugin you can try to get the latest version from github
